package com.drogaria.cotacao.model.enums;

public enum StatusPedido {
    PENDENTE_ENTREGA,
    CONFIRMADO_FORNECEDOR,
    ENTREGUE_SUCESSO,
    ENTREGUE_COM_FALTA,
    DIVERGENCIA, 
    VALORES_INCOMPATIVEIS,
    PENDENTE_DEVOLUCAO,
    CANCELADO
}